import os
import re
import psycopg2
from spotipy.oauth2 import SpotifyClientCredentials
import spotipy


SPOTIFY_CLIENT_ID = os.getenv("SPOTIFY_CLIENT_ID", "XXXX")
SPOTIFY_CLIENT_SECRET = os.getenv("SPOTIFY_CLIENT_SECRET", "XXXX")

sp = spotipy.Spotify(
    auth_manager=SpotifyClientCredentials(
        client_id=SPOTIFY_CLIENT_ID,
        client_secret=SPOTIFY_CLIENT_SECRET
    )
)


PG_HOST = os.getenv("PGHOST", "XXXX")
PG_PORT = int(os.getenv("PGPORT", "XXXX"))
PG_DB   = os.getenv("PGDATABASE", "XXXX")
PG_USER = os.getenv("PGUSER", "XXXX")
PG_PASS = os.getenv("PGPASSWORD", "XXXX")
PG_SCHEMA = os.getenv("PGSCHEMA", "XXXX")
PG_SSLMODE = os.getenv("PGSSL", "XXXX")  


conn = psycopg2.connect(
    host=PG_HOST,
    port=PG_PORT,
    dbname=PG_DB,
    user=PG_USER,
    password=PG_PASS,
    options=f"-c search_path={PG_SCHEMA}",
    sslmode=PG_SSLMODE
)
conn.autocommit = False
cur = conn.cursor()


create_table_sql = """
CREATE TABLE IF NOT EXISTS spotify_tracks (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    track_name VARCHAR(255),
    artist VARCHAR(255),
    album VARCHAR(255),
    popularity INTEGER,
    duration_minutes DOUBLE PRECISION
);
"""
cur.execute(create_table_sql)
conn.commit()


track_url = "https://open.spotify.com/track/3n3Ppam7vgaVa1iaRUc9Lp"
m = re.search(r"track/([a-zA-Z0-9]+)", track_url)
if not m:
    raise ValueError("Could not extract track ID from URL.")
track_id = m.group(1)


track = sp.track(track_id)

track_name = track["name"]
artist_name = track["artists"][0]["name"]
album_name = track["album"]["name"]
popularity = int(track["popularity"])
duration_minutes = float(track["duration_ms"]) / 60000.0


insert_sql = """
INSERT INTO spotify_tracks (track_name, artist, album, popularity, duration_minutes)
VALUES (%s, %s, %s, %s, %s)
RETURNING id;
"""
cur.execute(insert_sql, (track_name, artist_name, album_name, popularity, duration_minutes))
new_id = cur.fetchone()[0]
conn.commit()

print(f"Inserted track id={new_id}: '{track_name}' by {artist_name} (popularity={popularity}, duration={duration_minutes:.2f} min)")


cur.execute("""
SELECT track_name, artist, album, popularity
FROM spotify_tracks
ORDER BY popularity DESC
LIMIT 1;
""")
top = cur.fetchone()
if top:
    print(f"Top track now: {top[0]} by {top[1]} ({top[3]})")


cur.close()
conn.close()