import os
import re
import psycopg2
from spotipy.oauth2 import SpotifyClientCredentials
import spotipy


SPOTIFY_CLIENT_ID = os.getenv("SPOTIFY_CLIENT_ID", "850ed92fa6ba4f29909bd1ea7e64d66a")
SPOTIFY_CLIENT_SECRET = os.getenv("SPOTIFY_CLIENT_SECRET", "7849147f75b449278f501f9c3f5f1b15")

sp = spotipy.Spotify(
    auth_manager=SpotifyClientCredentials(
        client_id=SPOTIFY_CLIENT_ID,
        client_secret=SPOTIFY_CLIENT_SECRET
    )
)


PG_HOST = os.getenv("PGHOST", "INGLXDB84")
PG_PORT = int(os.getenv("PGPORT", "5432"))
PG_DB   = os.getenv("PGDATABASE", "support")
PG_USER = os.getenv("PGUSER", "c221100")
PG_PASS = os.getenv("PGPASSWORD", "c221100")
PG_SCHEMA = os.getenv("PGSCHEMA", "c221100")
PG_SSLMODE = os.getenv("PGSSL", "disable") 

conn = psycopg2.connect(
    host=PG_HOST,
    port=PG_PORT,
    dbname=PG_DB,
    user=PG_USER,
    password=PG_PASS,
    options=f"-c search_path={PG_SCHEMA}",
    sslmode=PG_SSLMODE
)
conn.autocommit = False
cur = conn.cursor()


cur.execute(f"CREATE SCHEMA IF NOT EXISTS {PG_SCHEMA};")
cur.execute("""
CREATE TABLE IF NOT EXISTS spotify_tracks (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    track_name VARCHAR(255),
    artist VARCHAR(255),
    album VARCHAR(255),
    popularity INTEGER,
    duration_minutes DOUBLE PRECISION
);
""")
conn.commit()


file_path = "track_urls.txt" 
with open(file_path, "r", encoding="utf-8") as f:
    track_urls = [line.strip() for line in f if line.strip() and not line.strip().startswith("#")]

ins_sql = """
INSERT INTO spotify_tracks (track_name, artist, album, popularity, duration_minutes)
VALUES (%s, %s, %s, %s, %s)
"""

processed = 0
errors = 0

for track_url in track_urls:
    try:
        m = re.search(r"track/([a-zA-Z0-9]+)", track_url)
        if not m:
            raise ValueError("Could not extract track ID from URL")
        track_id = m.group(1)

        track = sp.track(track_id)

        track_name = track["name"]
        artist_name = track["artists"][0]["name"]
        album_name = track["album"]["name"]
        popularity = int(track["popularity"])
        duration_minutes = float(track["duration_ms"]) / 60000.0

        cur.execute(
            ins_sql,
            (track_name, artist_name, album_name, popularity, duration_minutes)
        )
        processed += 1
        if processed % 50 == 0:
            conn.commit() 

        print(f"Inserted: {track_name} by {artist_name}")

    except Exception as e:
        errors += 1
        print(f"Error processing URL: {track_url} -> {e}")


conn.commit()
cur.close()
conn.close()

print(f"Done. Inserted={processed}, Errors={errors}")